FROM mysql:5.7
LABEL maintainer="hitchenlunwei@gmail.com"
COPY node-v8.12.0-linux-x64.tar.gz /home/node.tar.gz
RUN tar --strip-components 1 -xzf /home/node.tar.gz -C /usr/local
#设置免密登录
ENV MYSQL_USER demo
ENV MYSQL_PASSWORD 123456
ENV MYSQL_ROOT_PASSWORD 123456
#将所需文件放到容器中
COPY setup.sh /mysql/setup.sh
COPY schema.sql /mysql/schema.sql
COPY privileges.sql /mysql/privileges.sql

#设置容器启动时执行的命令
CMD ["sh", "/mysql/setup.sh"]